core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.homepage, name='home'),
    path('detail/<int:pk>/', views.detail_view, name='detail'),
    path('ask/', views.ask_question, name='ask'),
    path('update/<int:pk>/', views.update_question, name='update'),
    path('delete<int:pk>/', views.delete_view, name='delete'),
    path('like_post/<int:pk>/', views.like_post, name='like_post'),
    path('comment/reply/', views.reply_post, name="reply"),
]

studentproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('user/', include('user.urls', namespace='user')),
    # path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('signup/', views.register_page, name='signup'),
    path('logout/', views.logout_page, name='logout'),
    path('profile/<int:pk>/', views.user_profile, name='profile'),
    path('update_profile/<int:pk>/', views.edit_profile, name='update_profile'),
    
]

theme/templates/base.html
{% load static tailwind_tags %}
{% load crispy_forms_tags %}
{% load tailwind_filters %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&display=swap" rel="stylesheet">
		{% tailwind_css %}
	</head>
	<style>
		.nav-menu{
			display:none;
		}
	</style>

	<body class="bg-gray-50 leading-normal tracking-normal">
		<header class="w-full py-4 px-3 bg-white shadow-md">
          <nav class="flex items-center justify-between max-w-6xl m-auto">
			<a href="{% url 'core:home' %}" class="font-bold text-2xl px-2 py-1 rounded-md bg-indigo-500 text-white">Q</a>
             <div class="hidden md:block">
				<input class="p-3 border-none bg-gray-200 rounded-full w-96" placeholder="Search Qube">
			 </div>
			 
			 <button class=" z-50 block md:hidden" onclick="openNav()">
				<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
  <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
</svg>

			 </button>

			<div id="nav-menu" class="hidden md:block absolute md:relative top-0 md:top-auto pt-20 md:pt-0
			 bg-white h-full md:h-auto w-full md:w-auto left-0 md:left-auto text-center md:text-right">
{% if user.is_authenticated %}
	<a href="{% url 'user:profile' request.user.pk %}" class="ml-3 text-base block md:inline-block">Profile</a>
	<a href="{% url 'core:ask' %}" class="py-2 px-3 bg-indigo-500 rounded-md text-white ml-3 text-base block md:inline-block">+Post question</a>
	<a href="{% url 'user:logout' %}" class="ml-3 text-base block md:inline-block">Logout</a>

{% else %}
	<a href="{% url 'user:login' %}" class="ml-3 text-base block md:inline-block">Login</a>
	<a href="{% url 'user:signup' %}" class="py-2 px-3 bg-indigo-500 rounded-md text-white ml-3 text-base block md:inline-block">Sign Up</a>

{% endif %}

			</div>

		  </nav>
		</header>


    {% block content %}
    
    {% endblock %}


	<script>
		function openNav() {
            var e = document.getElementById('nav-menu');
            if (e.style.display == 'block')
            {
                e.style.display = 'none';
            }           
            else
            {
                e.style.display = 'block';
            }
        }
	</script>
	
	</body>
</html>