core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.homepage, name='home'),
    path('detail/<int:pk>/', views.detail_view, name='detail'),
    path('ask/', views.ask_question, name='ask'),
    path('update/<int:pk>/', views.update_question, name='update'),
    path('delete<int:pk>/', views.delete_view, name='delete'),
    path('like_post/<int:pk>/', views.like_post, name='like_post'),
    path('comment/reply/', views.reply_post, name="reply"),
]

studentproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('user/', include('user.urls', namespace='user')),
    # path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('signup/', views.register_page, name='signup'),
    path('logout/', views.logout_page, name='logout'),
    path('profile/<int:pk>/', views.user_profile, name='profile'),
    path('update_profile/<int:pk>/', views.edit_profile, name='update_profile'),
    
]

user/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User



class Profile(models.Model):
    user = models.OneToOneField(User, null=False, primary_key=True, on_delete=models.CASCADE)
    bio = models.TextField(null=True, blank=True)
    profile_pic = models.ImageField(default='static/default_profilepic/default.jpg', blank=True, upload_to='profile_pics')
    website_url = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return f'{self.user.username} Profile'

user/forms.py
from django.forms import ModelForm
from .models import *
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    profile_pic = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))

    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user']

user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.urls import reverse_lazy, reverse
from .forms import CreateUserForm, UpdateUserForm, ProfileUpdateForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout  # login
from .decorators import unauthenticated_user
from django.contrib.auth.decorators import login_required



# Create your views here.


@unauthenticated_user
def register_page(request):
    form = CreateUserForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, ' Account was created for ' + user)
            return redirect('user:login')
        else:
            messages.info(request, "Invalid username or password.")

    return render(request, 'user/signup.html', {'form': form})


@unauthenticated_user
def login_page(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect('core:home')
            else:
                messages.info(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    else:
        form = AuthenticationForm()
    return render(request=request, template_name="user/login.html", context={"form": form})


def logout_page(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect('core:home')


def user_profile(request, pk):
    user = User.objects.get(id=pk)
    return render(request, 'user/profile.html', {'user': user})


def edit_profile(request, pk):
    user = User.objects.get(id=pk)
    if request.method == "POST":
        u_form = UpdateUserForm(request.POST, request.FILES, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, "your account has been updated successfully!")
            return redirect('user:profile', pk)
    else:
        u_form = UpdateUserForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    return render(request, 'user/update_profile.html', {'user': user, 'u_form': u_form,
                                                        'p_form': p_form})

user/templates/user/login.html
{% extends 'base.html' %}
{%load crispy_forms_tags %} 
{% block content %}
<main class="max-w-2xl m-auto mt-10 px-3 py-3 bg-white">

    <form method="post" class="form_content">
       
        {% csrf_token %}
        {{ form|crispy }}


        <button type="submit" class="py-2 px-3 bg-indigo-500 rounded-md text-white ml-3 text-base">Login</button>

        <a class="signup_link" href="{% url 'user:signup' %}">Sign Up</a>


    </form>

</main>
{% endblock %}

user/templates/user/profile.html
{% extends 'base.html' %}

{% block content %}
<main class="max-w-2xl m-auto mt-10 px-3 py-3 bg-white">

<img id="image" src="{{ user.profile.profile_pic.url }}" class="h-40 w-40 shadow-md rounded-full object-cover align-middle">
<br>

<section style="margin-top: 10px;">
    <strong>{{user.username}}</strong>
    <br>
    <p>{{ user.email }}</p>

    {% if user.profile.bio %}
    <p>{{ user.profile.bio }}.</p>
   {% endif %}

   <br>

   {% if request.user == user %}
                    <a href="{% url 'user:update_profile' user.profile.pk %}" class="rounded-md bg-indigo-500 text-white px-3 py-2">Edit profile</a>
                    {% endif %}
</section>

</main>
{% endblock %}

user/templates/user/signup.html
{% extends 'base.html' %}
{%load crispy_forms_tags %}
{% block content %}

<main class="max-w-2xl m-auto mt-10 px-3 py-3 bg-white">
    <form method="POST" class="form_content">
        <h1>Signup</h1>
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="py-2 px-3 bg-indigo-500 rounded-md text-white ml-3 text-base">Signup</button>


        <a class="signup_link" href="{% url 'user:login' %}">Login</a>

    </form>

</main>
{% endblock %}

user/templates/user/update_profile.html
{% extends 'base.html' %}
{%load crispy_forms_tags %}


{% block content %}

<main class="max-w-2xl m-auto mt-10 px-3 py-3">

<form method="post" enctype="multipart/form-data" class="post_form">
    {% csrf_token %}

    {{ u_form|crispy}}
    {{ p_form|crispy }}

    <button class="py-2 px-3 bg-indigo-500 rounded-md text-white ml-3 text-base" type="submit">update profile</button>
</form>

</main>

{% endblock %}