core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.homepage, name='home'),
    path('detail/<int:pk>/', views.detail_view, name='detail'),
    path('ask/', views.ask_question, name='ask'),
    path('update/<int:pk>/', views.update_question, name='update'),
    path('delete<int:pk>/', views.delete_view, name='delete'),
    path('like_post/<int:pk>/', views.like_post, name='like_post'),
    path('comment/reply/', views.reply_post, name="reply"),
]

studentproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('user/', include('user.urls', namespace='user')),
    # path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('signup/', views.register_page, name='signup'),
    path('logout/', views.logout_page, name='logout'),
    path('profile/<int:pk>/', views.user_profile, name='profile'),
    path('update_profile/<int:pk>/', views.edit_profile, name='update_profile'),
    
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

    

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    question = models.TextField(null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='liked_posts')
    
    
    class Meta:
        ordering = ['-date_added']
        
        
    def __str__(self):
        return self.question
    
    def num_of_likes(self):
        return self.likes.count()
    
    def get_absolute_url(self):
        return reverse("core:detail", kwargs={"pk": self.pk})

    def get_comments(self):
        return self.comments.filter(parent=None).filter(active=True)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, related_name="comments")
    name = models.CharField(max_length=50, null=True)
    parent = models.ForeignKey("self", null=True, blank=True, on_delete=models.CASCADE)
    body = models.TextField(null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('date_created',)

    def __str__(self):
        return self.body

    def get_comments(self):
        return Comment.objects.filter(parent=self).filter(active=True)

    

    

core/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['question',]

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        

        

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . import views
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.http import JsonResponse
from django.urls import reverse


def homepage(request):
    posts = Post.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'core/home.html', context)


# detail

def detail_view(request, pk):
    post = get_object_or_404(Post, id=pk)
    comments = post.comments.filter(active=True)
    new_comment = None
    comment_count = post.comments.count()
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.name = request.user
            new_comment.post = post
            new_comment.save()
            return redirect('core:detail', pk)
    else:
        comment_form = CommentForm()

    return render(request, 'core/detail.html', {'post': post,
                                                   'comments': comments,
                                                   'new_comment':new_comment,
                                                   'comment_form': comment_form,
                                                   'comment_count': comment_count,
                                                   })


def reply_post(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            post_id = request.POST.get('post_id')
            parent_id = request.POST.get('parent')
            post_url = request.POST.get('post_url')
            reply = form.save(commit=False)
            reply.post = Post(id=post_id)
            reply.name = request.user
            reply.parent = Comment(id=parent_id)
            reply.save()
            return redirect(post_url,  reply.id)
    return redirect('/')


@login_required(login_url='user:login')
def ask_question(request):
    post = PostForm(request.POST)
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('core:home')
    else:
        form = PostForm()
    context = {
        'form': form
    }
    return render(request, 'core/ask.html', context)


# update post
@login_required(login_url='user:login')
def update_question(request, pk):
    update = get_object_or_404(Post, id=pk)
    form = PostForm(instance=update)
    if request.user == update.author:
        if request.method == 'POST':
            form = PostForm(request.POST, request.FILES, instance=update)
            if form.is_valid():
                form.save()
                messages.success(request, "item sucessfully updated")
                return redirect('core:home')

    else:
        return redirect('core:home')
    return render(request, 'core/update.html', {'form': form})


# delete post
@login_required(login_url='user:login')
def delete_view(request, pk):
    item = get_object_or_404(Post, id=pk)
    if request.user == item.author:
        if request.method == 'POST':
            item.delete()
            messages.success(request, "item sucessfully deleted")
            return redirect('core:home')
    else:
        return redirect('core:home')
    return render(request, 'core/delete.html', {'item': item})

@login_required(login_url='user:login')
def like_post(request, pk):
    post = Post.objects.get(id=pk)
    user = request.user
    if request.user in post.likes.all():
        post.likes.remove(user)
    else:
        post.likes.add(user)
    return redirect('core:detail', pk)

    

core/templates/core/ask.html
{% extends 'base.html' %} {%load crispy_forms_tags %} {% block content %}

<main class="max-w-2xl m-auto mt-10 px-3 py-3 bg-white">
  <form action="" method="POST">
    {% csrf_token %} {{form|crispy}}
    <button
      type="submit"
      class="py-2 px-3 bg-indigo-500 rounded-md text-white ml-3 text-base"
    >
      ASK QUESTION
    </button>
  </form>
</main>

{% endblock %}

core/templates/core/delete.html
<p>Are you sure you want to delete <strong>"{{ item }}"</strong></p>
<form action="{% url 'core:delete' item.id %}" method="POST">
    {% csrf_token %}
    <a href="{% url 'core:home' %}">Cancel</a>
    <button type="submit" name="confirm"
        style="padding: 5px; background-color: crimson; color: #fff; border: none;">delete please!</button>
</form>

core/templates/core/detail.html
{% extends 'base.html' %}
 {%load crispy_forms_tags %}
  {% block content %}
<style>
    textarea{
     height:60px;
    }
</style>
<main class="max-w-2xl m-auto mt-10 px-3 py-3 bg-white">
  <div class="user">
    <a
      href="{% url 'user:profile' post.author.profile.pk %}"
      class="flex items-center gap-2 mb-3"
    >
      <img
        src="{{post.author.profile.profile_pic.url}}"
        class="shadow-sm rounded-full h-9 w-9"
      />
      <h4 class="font-semibold hover:text-indigo-500 hover:underline">
        {{post.author}}
      </h4>
      <small>{{post.date_added}}</small></a
    >
  </div>
  <h2 class="font-semibold text-3xl mb-4">{{post.question}}</h2>

  {% if user.is_authenticated %} {% if request.user in post.likes.all %}
  <form method="post" action="{% url 'core:like_post' post.pk %}" class="mb-4">
    {% csrf_token %}
    <button type="submit" class="bg-red-500 py-1 px-3 text-white rounded-lg">
      downvote
    </button>
  </form>

  {% else %}
  <form method="post" action="{% url 'core:like_post' post.pk %}" class="mb-4">
    {% csrf_token %}
    <button type="submit" class="bg-indigo-500 py-1 px-3 text-white rounded-lg">
      upvote
    </button>
  </form>
  {% endif %} {% endif %}
  <p>{{ post.num_of_likes }} upvotes</p>

  {% if user.is_authenticated %} {% if request.user == post.author %}
  <a
    href="{% url 'core:update' post.pk %}"
    class="py-2 px-4 rounded-md bg-indigo-500 text-white text-sm"
    >Update</a
  >
  <a
    href="{% url 'core:delete' post.pk %}"
    class="py-2 px-4 rounded-md bg-red-500 text-white text-sm"
    >Delete</a
  >
  {% endif %} {% endif %}

  <br>

  <div class="comment-wrapper">

            <h2 class="font-semibold text-3xl mt-5 mb-3">Add Response</h2>
                 {% with comments.count as total_comments %}
            <h4>
                {{ total_comments }} response{{ total_comments|pluralize }}
            </h4>
        {% endwith %}
         {% if user.is_authenticated %}
        <form method="post" action=".">
            {% csrf_token %}
            {{ comment_form|crispy }}
            <button type="submit" class="px-4 py-2 bg-indigo-500 text-white text-sm rounded-md">Submit Response</button>
        </form>
         {% else %}
         <p>Please <a href="{% url 'user:login' %}">login </a>to comment</p>
          {% endif %}
        {% if not post.comments.all %}
            No comments yet

        {% else %}
            {% for comment in post.get_comments %}
                {% include 'core/response.html' with comment=comment %}
            {% endfor %}
        {% endif %}

          </div>

  <script>
  function openReply(response_id) {
    const reply_form_box = document.querySelector(`#reply-form-box-${response_id}`)
    if (reply_form_box) {
        reply_form_box.style.display = 'block';
    }

}
function cancelReply(response_id) {
    const reply_form_box = document.querySelector(`#reply-form-box-${response_id}`)
    if (reply_form_box) {
        reply_form_box.style.display = 'none';
    }
}
</script>
</main>

{% endblock %}

core/templates/core/home.html
{% extends 'base.html' %} {% block content %}

<main class="max-w-2xl m-auto mt-10 px-3 py-3">
  {% for post in posts %}
  <div class="mb-5 shadow-md hover:shadow-lg bg-white p-4">
    <div class="user">
      <a
        href="{% url 'user:profile' post.author.pk %}"
        class="flex items-center gap-2 mb-3"
      >
        <img
          src="{{post.author.profile.profile_pic.url}}"
          class="shadow-sm rounded-full h-9 w-9"
        />
        <h4 class="font-semibold hover:text-indigo-500 hover:underline">
          {{post.author}}
        </h4>
        <small>{{post.date_added}}</small></a
      >
    </div>
    <a
      href="{% url 'core:detail' post.pk %}"
      class="font-semibold text-lg hover:text-indigo-500 hover:underline"
      >{{post.question}}</a
    >
  </div>

  {% endfor %}
</main>
{% endblock %}

core/templates/core/response.html
<div class="border-l-2 pl-3" id="{{comment.id}}">
        <div class="mt-3">
            <strong>{{comment.name}}</strong>
            {% if  comment.parent.name%} to <strong>{{comment.parent.name}}</strong>{% endif %}
            <small>On {{ comment.date_created.date }}</small>
        </div>
        <div>
            <p>{{comment.body}}</p>

            {% if user.is_authenticated %}
            <button class="py-1 px-2 bg-gray-300 text-sm rounded-md" onclick="openReply({{comment.id}})">Reply</button>

           <div id="reply-form-box-{{comment.id}}" style="display:none">

                <form method="post" action="{% url 'core:reply' %}" style="margin-top:10px;">
                    {% csrf_token %}
                    <input type="hidden" name="post_id" value="{{post.id}}">
                    <input type="hidden" name="parent" value="{{comment.id}}">
                    <input type="hidden" name="post_url" value="{{post.get_absolute_url}}">
                    {{comment_form.as_p}}

                    <div class="mt-3">
                        <button type="button" onclick="cancelReply({{comment.id}})" class="py-1 px-3 bg-gray-300 rounded-md text-sm">Cancel</button>
                        <button type="submit" class="py-1 px-3 bg-indigo-500 rounded-md text-sm text-white">Submit</button>
                    </div>
                </form>
            </div>

            {% endif %}
        </div>
        {% for comment in comment.get_comments %}
            {% include 'core/response.html' with comment=comment %}
        {% endfor %}
</div>

core/templates/core/update.html
{% extends 'base.html' %} {%load crispy_forms_tags %} {% block content %}
<div class="ask-form">
  <form action="" method="POST">
    {% csrf_token %} {{form|crispy}}
    <button
      type="submit"
      class="py-2 px-3 bg-indigo-500 rounded-md text-white ml-3 text-base"
    >
      UPDATE QUESTION
    </button>
  </form>
</div>

{% endblock %}